name: Test Data Generator Script

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering from the GitHub UI

jobs:
  run-kotlin-job:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Java (Required by the Kotlin Compiler)
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      # Step 3: Install Kotlin Compiler on the runner
      - name: Set up Kotlin
        uses: fwilhe2/setup-kotlin@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_NUMBER }}:role/dpr-dpd-table-github-deploy-role
          aws-region: eu-west-2

      - name: Generate SQL
        id: generate_sql
        run: |
          chmod +x ./.github/scripts/script.main.kts
          
          SQL=$(kotlin ./.github/scripts/script.main.kts) 
          
          echo "sql<<EOF" >> $GITHUB_OUTPUT
          echo "$SQL" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Execute SQL in Redshift
        run: |
            aws redshift-data execute-statement \
              --cluster-identifier redshift-dev \
              --database database \
              --db-user user \
              --sql "${{ steps.generate_sql.outputs.sql }}"
    


