name: Validation

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  json-validation:
    runs-on: ubuntu-latest

    env:
      SCHEMA_LOCATION: "${{ github.workspace }}/schema.json"

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: "24.x"

      - name: SLSA
        uses: ministryofjustice/devsecops-actions/sca/slsa@a600477f79bedf31163091fad08150ab8b0b5be0

      - run: npm ci --ignore-scripts

      - name: Download schema
        run: curl --fail --silent --show-error https://raw.githubusercontent.com/ministryofjustice/hmpps-digital-prison-reporting-data-product-definitions-schema/main/schema/data-product-definition-schema.json -o $SCHEMA_LOCATION

      - name: Validate all the DPDs against the JSON schema
        id: validate-json
        run: npm run validate

      - name: Ensure variant uniqueness within DPDs
        id: ensure-uniqueness
        run: npm run uniqueness