name: Validation

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  json-validation:
    runs-on: ubuntu-latest

    env:
      SCHEMA_LOCATION: "${{ github.workspace }}/schema.json"

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Download schema
        run: curl https://raw.githubusercontent.com/ministryofjustice/hmpps-digital-prison-reporting-data-product-definitions-schema/main/schema/data-product-definition-schema.json -o $SCHEMA_LOCATION

      - name: Validate JSON
        id: validate-json
        uses: ammarlakis/action-ajv@445274826a4b7d391eb2b995e1414b669c10b6b9
        with:
          schema: ${{ env.SCHEMA_LOCATION }}
          data: "${{ github.workspace }}/dpd/**/*.json"
          allErrors: true

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: "24.x"

      - name: Ensure variant uniqueness within DPDs
        id: ensure-uniqueness
        run: node scripts/ensureUniqueness.js
